package org.barabari.mentoring.web;
import jakarta.validation.Valid;import jakarta.validation.constraints.*;import java.util.*;import org.barabari.mentoring.service.*;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api") @CrossOrigin(originPatterns={"http://localhost:*","http://127.0.0.1:*"},allowCredentials="true") public class ApiController {private final PlatformService data;private final JwtService jwt;private final EmailService email;public ApiController(PlatformService d,JwtService j,EmailService e){data=d;jwt=j;email=e;}
@GetMapping("/health")Map<String,Object>health(){return Map.of("status","UP","service","barabari-backend","storage","LOCAL_DEMO");}@PostMapping("/auth/login")Map<String,Object>login(@Valid@RequestBody Login r){return tokens(data.login(r.email,r.password).orElseThrow(()->new IllegalArgumentException("Invalid email or password")));}@PostMapping("/auth/refresh")Map<String,Object>refresh(@RequestBody Refresh r){var c=jwt.parse(r.refreshToken);if(!"refresh".equals(c.get("type",String.class)))throw new IllegalArgumentException("Invalid refresh token");return tokens(data.userByEmail(c.get("email",String.class)).orElseThrow());}@PostMapping("/auth/logout")@ResponseStatus(HttpStatus.NO_CONTENT)void logout(){}@GetMapping("/auth/me")PlatformService.UserView me(@RequestHeader("Authorization")String h){var c=jwt.parse(bearer(h));return data.userByEmail(c.get("email",String.class)).orElseThrow();}
@PostMapping("/admin/invitations")@ResponseStatus(HttpStatus.CREATED)PlatformService.InvitationView invite(@RequestBody Invite r){var invitation=data.invite(r.email,r.role.toUpperCase(),r.projectId);email.sendInvitation(invitation.email(),invitation.token(),invitation.role());return invitation;}@GetMapping("/admin/invitations")List<PlatformService.InvitationView>invitations(){return data.invitations();}@PostMapping("/invitations/{token}/accept")Map<String,Object>accept(@PathVariable String token,@Valid@RequestBody Accept r){return tokens(data.accept(token,r.name,r.password));}
@PostMapping("/admin/invitations/{id}/revoke")PlatformService.InvitationView revoke(@PathVariable String id){return data.revoke(id);}@GetMapping("/admin/users")List<PlatformService.UserView>users(){return data.users();}
@GetMapping("/invitations/{token}")PlatformService.InvitationView invitation(@PathVariable String token){return data.invitation(token);}@PostMapping("/auth/forgot-password")Map<String,String>forgot(@RequestBody Forgot r){data.createPasswordReset(r.email).ifPresent(t->email.sendPasswordReset(r.email,t));return Map.of("message","If that account exists, a reset link has been sent.");}@PostMapping("/auth/reset-password")Map<String,String>reset(@RequestBody Reset r){data.resetPassword(r.token,r.password);return Map.of("message","Password updated successfully.");}
@GetMapping("/projects")List<PlatformService.ProjectView>projects(){return data.projects();}@PostMapping("/projects")@ResponseStatus(HttpStatus.CREATED)PlatformService.ProjectView project(@Valid@RequestBody Project r){return data.createProject(r.name,r.summary);}@GetMapping("/projects/{id}/work")List<PlatformService.WorkItem>work(@PathVariable String id,@RequestParam(required=false)String type){return data.work(id,type);}@PostMapping("/projects/{id}/work")PlatformService.WorkItem work(@PathVariable String id,@RequestBody Work r){return data.createWork(id,r.type.toUpperCase(),r.title,r.description,r.status.toUpperCase(),r.priority.toUpperCase(),r.owner);}
@GetMapping("/escalations")List<PlatformService.Escalation>escalations(){return data.escalations();}@PostMapping("/escalations")PlatformService.Escalation escalate(@RequestBody Escalate r){return data.escalate(r.projectId,r.student,r.question,r.attemptedSolutions==null?List.of():r.attemptedSolutions,r.evidence==null?List.of():r.evidence,r.reason);}@PostMapping("/escalations/{id}/resolve")PlatformService.Escalation resolve(@PathVariable String id,@RequestBody Resolve r){return data.resolve(id,r.response,r.verified,r.reusableAsKnowledge);}@GetMapping("/admin/analytics")Map<String,Object>analytics(){return data.analytics();}
private Map<String,Object>tokens(PlatformService.UserView u){return Map.of("user",u,"accessToken",jwt.create(u.id(),u.email(),u.role(),900,"access"),"refreshToken",jwt.create(u.id(),u.email(),u.role(),604800,"refresh"));}private String bearer(String h){if(h==null||!h.startsWith("Bearer "))throw new IllegalArgumentException("Bearer token required");return h.substring(7);}public record Login(@Email String email,@NotBlank String password){}public record Refresh(String refreshToken){}public record Invite(@Email String email,String role,String projectId){}public record Accept(@NotBlank String name,@Size(min=10)String password){}public record Project(@NotBlank String name,@NotBlank String summary){}public record Work(String type,String title,String description,String status,String priority,String owner){}public record Escalate(String projectId,String student,String question,List<String>attemptedSolutions,List<Map<String,Object>>evidence,String reason){}public record Resolve(String response,boolean verified,boolean reusableAsKnowledge){}
public record Forgot(@Email String email){}public record Reset(String token,@Size(min=10)String password){}
}
