package org.barabari.mentoring.service;
import jakarta.annotation.PostConstruct;import java.security.SecureRandom;import java.time.Instant;import java.util.*;import java.util.concurrent.ConcurrentHashMap;import org.springframework.core.env.Environment;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.stereotype.Service;
@Service public class PlatformService {
 public record UserView(String id,String name,String email,String role){} public record ProjectView(String id,String name,String summary,String status,int health,int students,Instant createdAt){} public record InvitationView(String id,String email,String role,String projectId,String token,String status,Instant expiresAt){} public record WorkItem(String id,String projectId,String type,String title,String description,String status,String priority,String owner,Instant createdAt){} public record Escalation(String id,String projectId,String student,String question,List<String> attemptedSolutions,List<Map<String,Object>> evidence,String reason,String status,String mentorResponse,boolean verified,boolean reusableAsKnowledge,Instant createdAt){}
 static class Account{String id,name,email,role,passwordHash;Account(String i,String n,String e,String r,String p){id=i;name=n;email=e;role=r;passwordHash=p;}} static class Invite{String id,email,role,projectId,token,status;Instant expiresAt;Invite(String i,String e,String r,String p,String t){id=i;email=e;role=r;projectId=p;token=t;status="PENDING";expiresAt=Instant.now().plusSeconds(172800);}} static class Reset{String email,token;Instant expiresAt;boolean used;Reset(String e,String t){email=e;token=t;expiresAt=Instant.now().plusSeconds(1800);}}
 private final PasswordEncoder encoder;private final Environment env;private final SecureRandom random=new SecureRandom();private final Map<String,Account> users=new ConcurrentHashMap<>();private final Map<String,Invite> invitations=new ConcurrentHashMap<>();private final Map<String,Reset> resets=new ConcurrentHashMap<>();private final Map<String,ProjectView> projects=new ConcurrentHashMap<>();private final Map<String,WorkItem> work=new ConcurrentHashMap<>();private final Map<String,Escalation> escalations=new ConcurrentHashMap<>();public PlatformService(PasswordEncoder e,Environment v){encoder=e;env=v;}
 @PostConstruct void bootstrap(){String email=env.getProperty("app.bootstrap-admin.email","admin@barabari.local").toLowerCase();users.put(email,new Account(UUID.randomUUID().toString(),env.getProperty("app.bootstrap-admin.name","Administrator"),email,"ADMIN",encoder.encode(env.getProperty("app.bootstrap-admin.password","ChangeMe123!"))));seed();}void seed(){var a=createProject("Community Commerce","Marketplace enabling community entrepreneurs");var b=createProject("CareConnect Portal","Accessible care coordination portal");createWork(a.id(),"TASK","Confirm checkout acceptance criteria","Review delivery, refund, and payment edge cases","IN_PROGRESS","MEDIUM","Aarav");createWork(b.id(),"TICKET","OAuth redirect mismatch","Production callback differs from registered URI","OPEN","HIGH","Priya");}
 public Optional<UserView> login(String e,String p){var a=users.get(e.toLowerCase());return a!=null&&encoder.matches(p,a.passwordHash)?Optional.of(view(a)):Optional.empty();}public Optional<UserView> userByEmail(String e){return Optional.ofNullable(users.get(e.toLowerCase())).map(this::view);}private UserView view(Account a){return new UserView(a.id,a.name,a.email,a.role);}
 public List<UserView> users(){return users.values().stream().map(this::view).sorted(Comparator.comparing(UserView::name)).toList();}
 public InvitationView invite(String e,String r,String p){if(!Set.of("STUDENT","MENTOR","CLIENT","ADMIN").contains(r))throw new IllegalArgumentException("Invalid role");String t=token();var i=new Invite(UUID.randomUUID().toString(),e.toLowerCase(),r,p,t);invitations.put(t,i);return iv(i);}public List<InvitationView> invitations(){return invitations.values().stream().map(this::iv).toList();}private InvitationView iv(Invite i){return new InvitationView(i.id,i.email,i.role,i.projectId,i.token,i.status,i.expiresAt);}public UserView accept(String t,String n,String p){var i=invitations.get(t);if(i==null||!i.status.equals("PENDING")||i.expiresAt.isBefore(Instant.now()))throw new IllegalArgumentException("Invitation invalid or expired");if(users.containsKey(i.email))throw new IllegalArgumentException("Account exists");var a=new Account(UUID.randomUUID().toString(),n,i.email,i.role,encoder.encode(p));users.put(i.email,a);i.status="ACCEPTED";return view(a);}private String token(){byte[]b=new byte[24];random.nextBytes(b);return Base64.getUrlEncoder().withoutPadding().encodeToString(b);}
 public InvitationView invitation(String token){var i=invitations.get(token);if(i==null||!i.status.equals("PENDING")||i.expiresAt.isBefore(Instant.now()))throw new IllegalArgumentException("Invitation invalid or expired");return iv(i);}public Optional<String> createPasswordReset(String email){if(!users.containsKey(email.toLowerCase()))return Optional.empty();String t=token();resets.put(t,new Reset(email.toLowerCase(),t));return Optional.of(t);}public void resetPassword(String token,String password){var r=resets.get(token);if(r==null||r.used||r.expiresAt.isBefore(Instant.now()))throw new IllegalArgumentException("Reset link invalid or expired");users.get(r.email).passwordHash=encoder.encode(password);r.used=true;}
 public InvitationView revoke(String id){var i=invitations.values().stream().filter(x->x.id.equals(id)).findFirst().orElseThrow();if(i.status.equals("PENDING"))i.status="REVOKED";return iv(i);}
 public ProjectView createProject(String n,String s){String id=UUID.randomUUID().toString();var p=new ProjectView(id,n,s,"ACTIVE",75+random.nextInt(21),0,Instant.now());projects.put(id,p);return p;}public List<ProjectView> projects(){return projects.values().stream().sorted(Comparator.comparing(ProjectView::createdAt)).toList();}
 public WorkItem createWork(String p,String t,String title,String d,String s,String pr,String o){if(!projects.containsKey(p))throw new IllegalArgumentException("Project not found");String id=UUID.randomUUID().toString();var w=new WorkItem(id,p,t,title,d,s,pr,o,Instant.now());work.put(id,w);return w;}public List<WorkItem> work(String p,String t){return work.values().stream().filter(x->x.projectId.equals(p)&&(t==null||x.type.equalsIgnoreCase(t))).toList();}
 public Escalation escalate(String p,String s,String q,List<String>a,List<Map<String,Object>>e,String r){String id=UUID.randomUUID().toString();var x=new Escalation(id,p,s,q,a,e,r,"OPEN",null,false,false,Instant.now());escalations.put(id,x);return x;}public List<Escalation> escalations(){return List.copyOf(escalations.values());}public Escalation resolve(String id,String r,boolean v,boolean k){var o=Optional.ofNullable(escalations.get(id)).orElseThrow();var e=new Escalation(o.id,o.projectId,o.student,o.question,o.attemptedSolutions,o.evidence,o.reason,"RESOLVED",r,v,k,o.createdAt);escalations.put(id,e);return e;}public Map<String,Object> analytics(){return Map.of("activeProjects",projects.size(),"users",users.size(),"openTickets",work.values().stream().filter(x->x.status.equals("OPEN")).count(),"openEscalations",escalations.values().stream().filter(x->x.status.equals("OPEN")).count(),"selfResolvedRate",74,"mentorHoursSaved",41);}
}
